APP:
  MONGODB_RAW_URL: ''
  MONGODB_RAW_DB: ''
  MONGODB_RAW_COL: ''
  MONGODB_PROCESSED_URL: ''
  MONGODB_PROCESSED_DB: ''
  MONGODB_PROCESSED_COL: ''
  OSM_DATABASE_URL: ''
  REDIS_URL: ''
  SENDGRID_HOST: 'smtp.sendgrid.net'
  SENDGRID_HOST_USER: ''
  SENDGRID_HOST_PASSWORD: ''
