# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# ----- 
image: python:3.6.2
clone:
  depth: full

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - python --version
          - pip --version
          - pip install -r requirements.txt
          - python manage.py create_db
          - python manage.py migrate
          - ./run_tests.sh
        services:
          - mongo
          - postgres
          - redis          
  branches:
    master:
      - step:
          script: 
            - python --version
            - pip --version          
            - pip install -r requirements.txt
            - python manage.py create_db
            - python manage.py migrate            
            - ./run_tests.sh
            #- coverage report --fail-under=80            
          services:
            - mongo
            - postgres  
            - redis                             
      - step:
          name: Deploy to test
          caches:
            - pip
          deployment: test
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$TEST_APP.git HEAD
            - export HEROKU_APP="$TEST_APP"
            - ./run_migrations.sh
          services:
            - mongo 
            - postgres  
            - redis                   
      - step:
          name: Deploy to staging
          caches:
            - pip
          deployment: staging
          trigger: manual
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$STAGING_APP.git HEAD
          services:
            - mongo
            - postgres
            - redis
      - step:
          name: Deploy to production
          caches:
            - pip
          deployment: production
          trigger: manual
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$PRODUCTION_APP.git HEAD
          services:
            - mongo
            - postgres  
            - redis                                      
definitions: 
  services: 
    mongo: 
      image: mongo:3.4.10
    postgres: 
      image: postgres
    redis:
      image: redis